Companies/Models/ViewModels/OrganizationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Companies.ViewModels
{
    public class OrganizationsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OrganizationId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public int EmployeesCount { get; set; }
        public int CompetenciesCount { get; set; }
        public int OfficesCount { get; set; }
        public string ParentCompanyName { get; set; }
        public int? ParentId { get; set; }
        public List<UsersViewModel> Users { get; set; }
        public List<CompetenciesViewModel> Competencies { get; set; }
        public List<OfficesViewModel> Offices { get; set; }

    }
}

Companies/Controllers/CompetenceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Companies.Models;
using Companies.Database.Repository;
using Companies.Database.Models;
using Companies.DataManagers;
using Companies.ViewModels;

namespace Companies.Controllers
{
    public class CompetenceController : Controller
    {
        private OrganizationDataManager _organizationDataManager = null;
        private CompetenceDataManager _competenceDataManager = null;
        private CompetenceRepository _repository = null;

        public CompetenceController()
        {
            _organizationDataManager = new OrganizationDataManager();
            _competenceDataManager = new CompetenceDataManager();
            _repository = new CompetenceRepository();
        }















        // GET: Competences
        public ActionResult Index()
        {
            return View(_competenceDataManager.GetCompetenciesView());
        }

















        // GET: Competences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _competenceDataManager.GetCompetenceView(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            ViewData["OrganizationsList"] = _organizationDataManager.GetAllOrganizationsSelectList(model.OrganizationId);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "Id,Name,Description,Status,OrganizationId")] Competence competence, string submit)
        {
            //Navigation
            if (submit == "Save")
            {

                //Validation
                if (ModelState.IsValid)
                {
                    
                        var competenceData = new CompetenceRepository().GetById<Competence>(competence.Id);
                        //If organization changed
                        if (competenceData != null && competenceData.OrganizationId != competence.OrganizationId)
                        {
                            new UserRepository().RemoveUsersCompetence(competence.Id);
                        }

                    _repository.Update<Competence>(competence);

                    return RedirectToAction("Index");
                }


                return View(competence);


            }
            //Navigation
            else
            {
                return RedirectToAction("Index");
            }
        }














        // GET: Competences/Create
        public ActionResult Create()
        {
            ViewData["OrganizationsList"] = _organizationDataManager.GetAllOrganizationsSelectList();
            return View(new CompetenciesViewModel());
        }

        // POST: Competences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Status,OrganizationId")] Competence competence, string submit)
        {
            //Navigation
            if (submit == "Add")
            {
                //Validation
                if (ModelState.IsValid)
                {
                    _repository.Add<Competence>(competence);
                    return RedirectToAction("Index");
                }

                
                return View(competence);



            }
            //Navigation
            else
            {
                return RedirectToAction("Index");
            }
        }

        











        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}


        



    }
}

Companies/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Companies.Models;
using Companies.Database.Models;
using Companies.DataManagers;
using Companies.ViewModels;
using Companies.Database.Repository;

namespace Companies.Controllers
{
    public class UserController : Controller
    {
        private OrganizationDataManager _organizationDataManager = null;
        private OfficeDataManager _officeDataManager = null;
        private CompetenceDataManager _competenceDataManager = null;
        private UserDataManager _userDataManager = null;
        private UserRepository _repository = null;

        public UserController()
        {
            _organizationDataManager = new OrganizationDataManager();
            _officeDataManager = new OfficeDataManager();
            _competenceDataManager = new CompetenceDataManager();
            _userDataManager = new UserDataManager();
            _repository = new UserRepository();
        }














        // GET: Employee
        public ActionResult Index()
        {
            return View(_userDataManager.GetUsersView());
        }













        // GET: Employee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            UsersViewModel model = _userDataManager.GetUserView(id ?? 0);

            if (User == null)
            {
                return HttpNotFound();
            }

            User UserObject = _repository.GetById<User>(id ?? 0);

            if (model.LastEvaluation == -1)
                ViewData["LastEvaluation"] = "employee have not any evaluation";
            else
                ViewData["LastEvaluation"] = model.LastEvaluation + " (" + model.LastEvaluationDate + ")";

            ViewData["OrganizationsList"] = _organizationDataManager.GetAllOrganizationsSelectList(UserObject.OrganizationId);
            ViewData["CompetenciesList"] = _competenceDataManager.GetCompetenciesSelectListByOrganization(UserObject.OrganizationId, UserObject.CompetenceId);
            ViewData["OfficesList"] = _officeDataManager.GetAllOfficesSelectList(UserObject.OrganizationId, UserObject.OfficeId);


            return View(model);
        }
        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "Id,Name,LastName,Email,PhoneNumber,RegistrationDate,OrganizationId,CompetenceId,OfficeId")] User model, string submit)
        {
            //Navigation
            if (submit == "Save")
            {
                
                //Validation
                if (ModelState.IsValid)
                {
                    var User = _repository.GetById<User>(model.Id);


                    //When changes organization office and competence is null.
                    if (model.OrganizationId != User.OrganizationId)
                    {
                        model.CompetenceId = null;
                        model.OfficeId = null;
                    }


                    //Update
                    _repository.Update<User>(model);
                    
                    return RedirectToAction("Index");
                }
                
                return View(model.Id);

            }
            //Navigation
            else
            {
                return RedirectToAction("Index");
            }
        }










        // GET: Employee/Create
        public ActionResult Create()
        {
            ViewData["OrganizationsList"] = _organizationDataManager.GetAllOrganizationsSelectList();
            //ViewData["CompetenciesList"] = _competenceDataManager.GetCompetenciesSelectListByOrganization(UserObject.OrganizationId, UserObject.CompetenceId);
            //ViewData["OfficesList"] = _officeDataManager.GetAllOfficesSelectList(UserObject.OrganizationId, UserObject.OfficeId);
            return View(new UsersViewModel());
        }

        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,LastName,Email,PhoneNumber,RegistrationDate,OrganizationId,CompetenceId,OfficeId")] User User, string submit)
        {
            //Navigation
            if (submit == "Add")
            {
                User.RegistrationDate = DateTime.Now;


                //Validation
                if (ModelState.IsValid)
                {
                    _repository.Add<User>(User);
                    return RedirectToAction("Index");
                }
                
                return View(User);

            }
            //Navigation
            else
            {
                return RedirectToAction("Index");
            }
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Companies/Views/Organization/Create.cshtml
@model Companies.ViewModels.OrganizationsViewModel

@{
    ViewBag.Title = "New company";
}

<div class="container">

    @*For spacing*@
    <div class="row">
        <div class="col-sm-12" style="height:50px;"></div>
    </div>

    <div class="row">
        <div class="col-sm-12">




            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="panel panel-default">
                    <div class="panel-heading"><h2>Add new company</h2></div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <h4>Organization</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ParentId, "Parent company", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("ParentId", (System.Collections.Generic.IEnumerable<System.Web.Mvc.SelectListItem>)ViewData["OrganizationsList"], "", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                    </div>




                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-2 col-sm-offset-2" style="display:inline;">
                                
                                <input name="submit" type="submit" value="Add" class="btn btn-success" />
                                <input name="submit" type="submit" value="Cancel" class="btn btn-danger" />

                            </div>
                        </div>
                        
                    </div>
                </div>
            }

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Companies/Views/Organization/Delete.cshtml
@model Companies.ViewModels.OrganizationsViewModel

@{
    ViewBag.Title = "Delete company";
}

<div class="container">



    @*For spacing*@
    <div class="row">
        <div class="col-sm-12" style="height:50px;"></div>
    </div>



    <div class="row text-center">

        <div class="col-sm-12">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2>Delete</h2>

                    <h3>Are you sure you want to delete this company?</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-bordered table-responsive table-hover">
                        <thead>
                            <tr class="danger">
                                <th class="text-center">Name</th>
                                <th class="text-center">Description</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Parent company</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="danger">
                                <td>@Html.ActionLink(Model.Name, "Details", "Competence", new { id = Model.Id }, null)</td>
                                <td>@Model.Description</td>
                                <td>@Model.Status</td>
                                <td>@Model.ParentCompanyName</td>
                            </tr>
                    </table>



                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input name="submit" type="submit" value="Delete" class="btn btn-danger" />
                            <input name="submit" type="submit" value="Back" class="btn btn-default" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Companies/Views/Organization/Details.cshtml
@model Companies.ViewModels.OrganizationsViewModel

@{
    ViewBag.Title = "Company details";
}


<div class="container content">


    @*For spacing*@
    <div class="row">
        <div class="col-sm-12" style="height:50px;"></div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-4">
                                <h1>Company</h1>
                                <h5>Created date: @Model.CreatedDate</h5>
                                <div class="panel panel-default">
                                    <div class="panel-body">






                                        @using (Html.BeginForm())
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                            @Html.HiddenFor(model => model.Id)
                                            @Html.HiddenFor(model => model.Status)
                                            @Html.HiddenFor(model => model.CreatedDate)

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Name, "Name:", htmlAttributes: new { @class = "control-label col-md-2" })
                                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            </div>


                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Description, "Description:", htmlAttributes: new { @class = "control-label col-md-2" })
                                                @Html.TextArea("Description", Model.Description, new { rows = 7, @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                            </div>

                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <p><h4>Status:</h4> @Model.Status</p>
                                                </div>
                                                <div class="panel-body">
                                                    <div class="form-group">
                                                        @Html.LabelFor(model => model.ParentId, "Parent company:", htmlAttributes: new { style = "width:auto", @class = "control-label col-md-2" })
                                                        @Html.DropDownListFor(model => model.ParentId, (System.Collections.Generic.IEnumerable<System.Web.Mvc.SelectListItem>)ViewData["OrganizationsList"], "", new { @class = "form-control" })
                                                        @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-sm-12">
                                                    <input name="submit" type="submit" value="Save" class="btn btn-success" />
                                                    <input name="submit" type="submit" value="Delete" class="btn btn-danger" />
                                                    <input name="submit" type="submit" value="Back" class="btn btn-default" />
                                                </div>
                                            </div>
                                        }










                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h2>Company competencies</h2>
                                    </div>
                                    <div class="panel-body">
                                        <table class="table table-bordered table-responsive table-hover">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Competence</th>
                                                    <th class="text-center">Description</th>
                                                    <th class="text-center">Status</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var competence in Model.Competencies)
                                                {
                                                    <tr>
                                                        <td class="text-center">@Html.ActionLink(competence.Name, "Details", "Competence", new { id = competence.Id }, null)</td>
                                                        <td class="text-center">@competence.Description</td>
                                                        <td class="text-center">@competence.Status</td>
                                                    </tr>
                                                }
                                        </table>
                                    </div>
                                </div>


                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h2>Company employees</h2>
                                    </div>
                                    <div class="panel-body">
                                        <table class="table table-bordered table-responsive table-hover">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">User</th>
                                                    <th class="text-center">Office</th>
                                                    <th class="text-center">Competence</th>
                                                    <th class="text-center">Last evaluation</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var user in Model.Users.Select((value, i) => new { i, value }))
                                                {
                                                    <tr>
                                                        <td class="text-center">@Html.ActionLink(user.value.Name, "Details", "User", new { id = user.value.Id }, null)</td>
                                                        <td class="text-center">@user.value.OfficeName</td>
                                                        <td class="text-center">@user.value.CompetenceName</td>
                                                        <td class="text-center">@{var echo = ((List<string>)ViewData["LastEvaluation"])[user.i];} @echo</td>
                                                    </tr>
                                                }
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="row">
                            <div class="col-sm12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h2>Company offices</h2>
                                    </div>
                                    <div class="panel-body">
                                        <table class="table table-bordered table-responsive table-hover">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Name</th>
                                                    <th class="text-center">Description</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var office in Model.Offices)
                                                {
                                                    <tr>
                                                        <td class="text-center">@office.Name</td>
                                                        <td class="text-center">@office.Description</td>
                                                    </tr>
                                                            }
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>








                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Companies/Views/Organization/Index.cshtml
@model List<Companies.ViewModels.OrganizationsViewModel>

@{
    ViewBag.Title = "Companies";
}


<div class="container content">


    @*For spacing*@
    <div class="row">
        <div class="col-sm-12" style="height:50px;"></div>
    </div>

    <div class="row">
        <div class="col-sm-6 text-left">
            <h1>Companies</h1>
        </div>
        <div class="col-sm-6 text-right">
            @using (Html.BeginForm("Create", "Organization", FormMethod.Get))
            {
                <button type="submit" class="btn btn-default" style="margin-top:27px">Add new</button>
            }
        </div>
    </div>

    @*For spacing*@
    <div class="row">
        <div class="col-sm-12" style="height:50px;"></div>
    </div>



    <div class="row text-center">
        <table class="table table-bordered table-responsive table-hover">
            <thead>
                <tr>
                    <th class="text-center">Company</th>
                    <th class="text-center">Employees count</th>
                    <th class="text-center">Competencies count</th>
                    <th class="text-center">Offices count</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var organization in Model)
                {
                    <tr>
                        <td>@Html.ActionLink(organization.Name, "Details", "Organization", new { id = organization.Id }, null)</td>
                        <td>@organization.EmployeesCount</td>
                        <td>@organization.CompetenciesCount</td>
                        <td>@organization.OfficesCount</td>
                    </tr>
                }
                </tbody>
        </table>
    </div>
</div>