Companies/Models/ViewModels/OfficesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Companies.ViewModels
{
    public class OfficesViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }

    }
}

Companies/Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Companies.Models;
using Companies.DataManagers;
using Companies.ViewModels;
using Companies.Database.Models;
using Companies.Database.Repository;

namespace Companies.Controllers
{
    public class OfficeController : Controller
    {
        private OrganizationDataManager _organizationDataManager = null;
        private OfficeDataManager _officeDataManager = null;
        private OfficeRepository _repository = null;

        public OfficeController()
        {
            _organizationDataManager = new OrganizationDataManager();
            _officeDataManager = new OfficeDataManager();
            _repository = new OfficeRepository();
        }










        // GET: Offices
        public ActionResult Index()
        {
            return View(_officeDataManager.GetOfficesView());
        }












        // GET: Offices/Create
        public ActionResult Create()
        {
            ViewData["OrganizationsList"] = _organizationDataManager.GetAllOrganizationsSelectList();
            return View(new OfficesViewModel());
        }

        // POST: Offices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,OrganizationId")] Office office, string submit)
        {
            //Navigation
            if (submit == "Add")
            {

            //Validation
            if (ModelState.IsValid)
            {
                _repository.Add<Office>(office);
                return RedirectToAction("Index");
            }



            return View(office);


            }
            //Navigation
            else
            {
                return RedirectToAction("Index");
            }
        }

        






        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}















    }
}

Companies/Views/Office/Create.cshtml
@model Companies.ViewModels.OfficesViewModel


@{
    ViewBag.Title = "New office";
}

<div class="container">

    @*For spacing*@
    <div class="row">
        <div class="col-sm-12" style="height:50px;"></div>
    </div>


    <div class="row">
        <div class="col-sm-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Add new office</h2>
                    </div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <h4>Office</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="well">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.OrganizationId, "Organization", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("OrganizationId", (System.Collections.Generic.IEnumerable<System.Web.Mvc.SelectListItem>)ViewData["OrganizationsList"], htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextArea("Description", new { rows = 7, @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-md-offset-2 col-md-10" style="display:inline;">
                                    <input name="submit" type="submit" value="Add" class="btn btn-success" />
                                    <input name="submit" type="submit" value="Cancel" class="btn btn-danger" />
                                </div>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>

Companies/Views/Office/Index.cshtml
@model List<Companies.ViewModels.OfficesViewModel>


@{
    ViewBag.Title = "Offices Index";
}


    <div class="container content">


        @*For spacing*@
        <div class="row">
            <div class="col-sm-12" style="height:50px;"></div>
        </div>

        <div class="row">
            <div class="col-sm-6 text-left">
                <h1>Offices</h1>
            </div>
            <div class="col-sm-6 text-right">
                @using (Html.BeginForm("Create", "Office", FormMethod.Get))
                {
                    <button type="submit" class="btn btn-default" style="margin-top:27px">Add new</button>
                }
            </div>
        </div>

        @*For spacing*@
        <div class="row">
            <div class="col-sm-12" style="height:50px;"></div>
        </div>





        <div class="row text-center">

            <table class="table table-bordered table-responsive table-hover">
                <thead>
                    <tr>
                        <th class="text-center">Name</th>
                        <th class="text-center">Description</th>
                        <th class="text-center">Organizationa name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var office in Model)
                    {
                        <tr>
                            <td class="text-center">@office.Name</td>
                            <td class="text-center">@office.Description</td>
                            <td class="text-center">@office.OrganizationName</td>
                        </tr>
                    }
                </tbody>
            </table>



        </div>

    </div>